@echo off
echo Starting Backend Server...
start "Backend Server" cmd /k "cd web-app\server && node server.js"
timeout /t 2 >nul
echo Starting Frontend Client...
start "Frontend Client" cmd /k "cd web-app\client && npm run dev"
echo Application launching...
pause
